//! phux-vt-web — a Rust/WASM driver for ghostty's `libghostty-vt` terminal
//! engine, compiled to WebAssembly (`ghostty-vt.wasm`).
//!
//! The phux browser client renders terminals with the *same* VT engine native
//! phux uses. Rather than link zig into the Rust wasm binary, we load
//! `ghostty-vt.wasm` as a separate module — it is self-contained (its only
//! import is `env.log`) and ships its own allocator — and drive its C ABI
//! through the WebAssembly JS API. This module is the thin, safe Rust surface
//! over that ABI.
//!
//! The ABI is the public `libghostty-vt` C surface (`include/ghostty/vt.h`).
//! Pointers are offsets into the engine module's linear memory; by-value
//! structs (e.g. `GhosttyTerminalOptions`) lower to a pointer argument. The
//! call/marshal patterns here mirror `libghostty-vt`'s safe wrapper
//! (`terminal.rs` / `render.rs`), validated against the real module.

#![deny(missing_docs)]

use std::rc::Rc;

use js_sys::{Array, Function, Object, Reflect, Uint8Array, WebAssembly};
use wasm_bindgen::JsCast;
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;

/// The embedded ghostty-vt engine module. Regenerated by
/// `scripts/build-vt-wasm.sh` (gitignored build artifact).
static GHOSTTY_VT_WASM: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/vendor/ghostty-vt.wasm"
));

/// Size of the embedded engine module, in bytes.
#[must_use]
pub const fn engine_wasm_len() -> usize {
    GHOSTTY_VT_WASM.len()
}

// ── ABI constants (from include/ghostty/vt.h) ────────────────────────────────
const GHOSTTY_SUCCESS: i32 = 0;
// RenderStateData (whole-frame reads via ghostty_render_state_get)
const RENDER_STATE_DATA_COLS: f64 = 1.0;
const RENDER_STATE_DATA_ROWS: f64 = 2.0;
const RENDER_STATE_DATA_ROW_ITERATOR: f64 = 4.0;
const RENDER_STATE_DATA_COLOR_BG: f64 = 5.0;
const RENDER_STATE_DATA_COLOR_FG: f64 = 6.0;
// RenderStateRowData (per-row reads via ghostty_render_state_row_get)
const RENDER_STATE_ROW_DATA_CELLS: f64 = 3.0;

// `ghostty_terminal_get` data tags (GhosttyTerminalData in ghostty/vt/terminal.h).
const TERMINAL_DATA_CURSOR_X: f64 = 3.0;
const TERMINAL_DATA_CURSOR_Y: f64 = 4.0;
const TERMINAL_DATA_CURSOR_VISIBLE: f64 = 7.0;
// RenderStateRowCellsData (per-cell reads via ghostty_render_state_row_cells_get)
const ROW_CELLS_DATA_GRAPHEMES_LEN: f64 = 3.0;
const ROW_CELLS_DATA_GRAPHEMES_BUF: f64 = 4.0;
const ROW_CELLS_DATA_BG_COLOR: f64 = 5.0;
const ROW_CELLS_DATA_FG_COLOR: f64 = 6.0;

/// An 8-bit RGB color.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Rgb {
    /// Red channel.
    pub r: u8,
    /// Green channel.
    pub g: u8,
    /// Blue channel.
    pub b: u8,
}

/// One rendered cell: its base grapheme and resolved fg/bg (None = use the
/// grid default).
#[derive(Clone, Debug)]
pub struct GridCell {
    /// Base grapheme (combining marks are dropped for now).
    pub ch: char,
    /// Explicit foreground color, if any.
    pub fg: Option<Rgb>,
    /// Explicit background color, if any.
    pub bg: Option<Rgb>,
}

/// A full styled snapshot of the visible grid, ready for a renderer. `cells` is
/// row-major, `cols * rows` long.
#[derive(Clone, Debug)]
pub struct Grid {
    /// Columns.
    pub cols: u16,
    /// Rows.
    pub rows: u16,
    /// Default foreground (terminal palette).
    pub default_fg: Rgb,
    /// Default background (terminal palette).
    pub default_bg: Rgb,
    /// Row-major cells, `cols * rows` entries.
    pub cells: Vec<GridCell>,
    /// Cursor column (0-indexed) within the active area.
    pub cursor_col: u16,
    /// Cursor row (0-indexed) within the active area.
    pub cursor_row: u16,
    /// Whether the cursor is visible (DEC mode 25).
    pub cursor_visible: bool,
}

/// A loaded ghostty-vt engine instance. Holds the WebAssembly instance, its
/// linear memory, and cached handles to the C ABI exports the client uses.
pub struct Vt {
    memory: WebAssembly::Memory,
    alloc: Function,
    free: Function,
    terminal_new: Function,
    terminal_free: Function,
    terminal_get: Function,
    vt_write: Function,
    resize: Function,
    rs_new: Function,
    rs_update: Function,
    rs_get: Function,
    row_iter_new: Function,
    row_iter_next: Function,
    row_get: Function,
    cells_new: Function,
    cells_next: Function,
    cells_get: Function,
}

impl Vt {
    /// Instantiate the engine module. Async because WebAssembly instantiation
    /// is; the only host import the module needs is `env.log`.
    ///
    /// # Errors
    /// Returns the underlying `JsValue` if instantiation fails or an expected
    /// export is missing.
    pub async fn load() -> Result<Rc<Self>, JsValue> {
        let env = Object::new();
        Reflect::set(&env, &"log".into(), &Function::new_no_args(""))?;
        let imports = Object::new();
        Reflect::set(&imports, &"env".into(), &env)?;

        let result =
            JsFuture::from(WebAssembly::instantiate_buffer(GHOSTTY_VT_WASM, &imports)).await?;
        let instance: WebAssembly::Instance =
            Reflect::get(&result, &"instance".into())?.dyn_into()?;
        let exports = instance.exports();
        let memory: WebAssembly::Memory = Reflect::get(&exports, &"memory".into())?.dyn_into()?;

        let f = |name: &str| -> Result<Function, JsValue> {
            Reflect::get(&exports, &JsValue::from_str(name))?
                .dyn_into::<Function>()
                .map_err(|_| JsValue::from_str(&format!("missing export: {name}")))
        };

        Ok(Rc::new(Self {
            memory,
            alloc: f("ghostty_wasm_alloc_u8_array")?,
            free: f("ghostty_wasm_free_u8_array")?,
            terminal_new: f("ghostty_terminal_new")?,
            terminal_free: f("ghostty_terminal_free")?,
            terminal_get: f("ghostty_terminal_get")?,
            vt_write: f("ghostty_terminal_vt_write")?,
            resize: f("ghostty_terminal_resize")?,
            rs_new: f("ghostty_render_state_new")?,
            rs_update: f("ghostty_render_state_update")?,
            rs_get: f("ghostty_render_state_get")?,
            row_iter_new: f("ghostty_render_state_row_iterator_new")?,
            row_iter_next: f("ghostty_render_state_row_iterator_next")?,
            row_get: f("ghostty_render_state_row_get")?,
            cells_new: f("ghostty_render_state_row_cells_new")?,
            cells_next: f("ghostty_render_state_row_cells_next")?,
            cells_get: f("ghostty_render_state_row_cells_get")?,
        }))
    }

    /// Open a terminal of `cols`×`rows`, with its own render state + reusable
    /// row/cell iterators and scratch buffers.
    #[must_use]
    pub fn terminal(self: &Rc<Self>, cols: u16, rows: u16) -> Terminal {
        // GhosttyTerminalOptions (wasm32): cols u16@0, rows u16@2, scrollback u32@4.
        let opts = self.wasm_alloc(8);
        self.w_u16(opts, cols);
        self.w_u16(opts + 2, rows);
        self.w_u32(opts + 4, 5_000);

        let term_out = self.wasm_alloc(4);
        let _ = self.call(
            &self.terminal_new,
            &[0.0, f64::from(term_out), f64::from(opts)],
        );
        let term = self.r_u32(term_out);

        let state_out = self.wasm_alloc(4);
        let _ = self.call(&self.rs_new, &[0.0, f64::from(state_out)]);
        let state = self.r_u32(state_out);

        // iter_slot holds the row-iterator handle; rebound from the render
        // state on every read (render_state_get rewrites it in place).
        let iter_slot = self.wasm_alloc(4);
        let _ = self.call(&self.row_iter_new, &[0.0, f64::from(iter_slot)]);

        // cells_slot holds the cell-container handle; rebound per row via
        // render_state_row_get(CELLS), which rewrites it in place (like iter_slot).
        let cells_slot = self.wasm_alloc(4);
        let _ = self.call(&self.cells_new, &[0.0, f64::from(cells_slot)]);

        Terminal {
            vt: Rc::clone(self),
            term,
            state,
            iter_slot,
            cells_slot,
            scratch: self.wasm_alloc(8),
            grapheme_buf: self.wasm_alloc(256),
        }
    }

    // ── call + memory marshalling ────────────────────────────────────────────

    fn call(&self, func: &Function, args: &[f64]) -> f64 {
        let arr = Array::new();
        for a in args {
            arr.push(&JsValue::from_f64(*a));
        }
        func.apply(&JsValue::NULL, &arr)
            .ok()
            .and_then(|v| v.as_f64())
            .unwrap_or(0.0)
    }

    fn wasm_alloc(&self, len: u32) -> u32 {
        self.call(&self.alloc, &[f64::from(len)]) as u32
    }

    // A fresh view each access: the ArrayBuffer detaches whenever the engine
    // grows its memory, but offsets stay valid (wasm memory only grows).
    fn bytes(&self) -> Uint8Array {
        Uint8Array::new(&self.memory.buffer())
    }

    fn w_u16(&self, ptr: u32, v: u16) {
        let b = self.bytes();
        b.set_index(ptr, v as u8);
        b.set_index(ptr + 1, (v >> 8) as u8);
    }

    fn w_u32(&self, ptr: u32, v: u32) {
        let b = self.bytes();
        for i in 0..4 {
            b.set_index(ptr + i, (v >> (8 * i)) as u8);
        }
    }

    fn r_u32(&self, ptr: u32) -> u32 {
        let b = self.bytes();
        u32::from(b.get_index(ptr))
            | (u32::from(b.get_index(ptr + 1)) << 8)
            | (u32::from(b.get_index(ptr + 2)) << 16)
            | (u32::from(b.get_index(ptr + 3)) << 24)
    }

    fn r_u8(&self, ptr: u32) -> u8 {
        self.bytes().get_index(ptr)
    }

    fn w_bytes(&self, ptr: u32, data: &[u8]) {
        self.bytes()
            .subarray(ptr, ptr + data.len() as u32)
            .copy_from(data);
    }
}

/// An open terminal: a libghostty terminal grid + render state, driven by a
/// [`Vt`] engine. Feed it VT bytes with [`Terminal::write`] and read the grid
/// back with [`Terminal::rows_text`] (text) for rendering.
pub struct Terminal {
    vt: Rc<Vt>,
    term: u32,
    state: u32,
    iter_slot: u32,
    cells_slot: u32,
    scratch: u32,
    grapheme_buf: u32,
}

impl Terminal {
    /// Feed VT-encoded bytes (PTY output) through the terminal's parser.
    pub fn write(&self, data: &[u8]) {
        if data.is_empty() {
            return;
        }
        let ptr = self.vt.wasm_alloc(data.len() as u32);
        self.vt.w_bytes(ptr, data);
        let _ = self.vt.call(
            &self.vt.vt_write,
            &[f64::from(self.term), f64::from(ptr), data.len() as f64],
        );
        let _ = self
            .vt
            .call(&self.vt.free, &[f64::from(ptr), data.len() as f64]);
    }

    /// Resize the terminal grid to `cols`×`rows` (cell pixel size is advisory).
    pub fn resize(&self, cols: u16, rows: u16, cell_w_px: u32, cell_h_px: u32) {
        let _ = self.vt.call(
            &self.vt.resize,
            &[
                f64::from(self.term),
                f64::from(cols),
                f64::from(rows),
                f64::from(cell_w_px),
                f64::from(cell_h_px),
            ],
        );
    }

    /// Read the visible grid back as one `String` per row (text only; styling
    /// is read separately by the renderer). Trailing blanks are trimmed.
    #[must_use]
    pub fn rows_text(&self) -> Vec<String> {
        let vt = &*self.vt;
        let _ = vt.call(
            &vt.rs_update,
            &[f64::from(self.state), f64::from(self.term)],
        );
        // Bind the row iterator to the current render state (rewrites iter_slot).
        let _ = vt.call(
            &vt.rs_get,
            &[
                f64::from(self.state),
                RENDER_STATE_DATA_ROW_ITERATOR,
                f64::from(self.iter_slot),
            ],
        );
        let iter = vt.r_u32(self.iter_slot);

        let mut lines = Vec::new();
        while vt.call(&vt.row_iter_next, &[f64::from(iter)]) as i32 != 0 {
            // Bind the cell container to this row (rewrites cells_slot in place).
            let _ = vt.call(
                &vt.row_get,
                &[
                    f64::from(iter),
                    RENDER_STATE_ROW_DATA_CELLS,
                    f64::from(self.cells_slot),
                ],
            );
            let cells = vt.r_u32(self.cells_slot);
            let mut line = String::new();
            while vt.call(&vt.cells_next, &[f64::from(cells)]) as i32 != 0 {
                line.push(self.cell_base_char(cells));
            }
            lines.push(line.trim_end().to_string());
        }
        lines
    }

    /// The base grapheme of the current cell (or space if blank/unreadable).
    fn cell_base_char(&self, cells: u32) -> char {
        let vt = &*self.vt;
        let r = vt.call(
            &vt.cells_get,
            &[
                f64::from(cells),
                ROW_CELLS_DATA_GRAPHEMES_LEN,
                f64::from(self.scratch),
            ],
        ) as i32;
        if r != GHOSTTY_SUCCESS || vt.r_u32(self.scratch) == 0 {
            return ' ';
        }
        let r2 = vt.call(
            &vt.cells_get,
            &[
                f64::from(cells),
                ROW_CELLS_DATA_GRAPHEMES_BUF,
                f64::from(self.grapheme_buf),
            ],
        ) as i32;
        if r2 != GHOSTTY_SUCCESS {
            return ' ';
        }
        char::from_u32(vt.r_u32(self.grapheme_buf)).unwrap_or(' ')
    }

    /// Read the full styled grid for rendering: per-cell grapheme + resolved
    /// fg/bg, plus the terminal's default fg/bg. Rows are padded to `cols`.
    #[must_use]
    pub fn grid(&self) -> Grid {
        let vt = &*self.vt;
        let _ = vt.call(
            &vt.rs_update,
            &[f64::from(self.state), f64::from(self.term)],
        );

        let cols = self.rs_u32(RENDER_STATE_DATA_COLS) as u16;
        let rows = self.rs_u32(RENDER_STATE_DATA_ROWS) as u16;
        let default_fg = self.rs_color(RENDER_STATE_DATA_COLOR_FG).unwrap_or(Rgb {
            r: 0xd7,
            g: 0xd7,
            b: 0xdd,
        });
        let default_bg = self.rs_color(RENDER_STATE_DATA_COLOR_BG).unwrap_or(Rgb {
            r: 0x0b,
            g: 0x0b,
            b: 0x0f,
        });

        let _ = vt.call(
            &vt.rs_get,
            &[
                f64::from(self.state),
                RENDER_STATE_DATA_ROW_ITERATOR,
                f64::from(self.iter_slot),
            ],
        );
        let iter = vt.r_u32(self.iter_slot);

        let mut cells = Vec::with_capacity(usize::from(cols) * usize::from(rows));
        while vt.call(&vt.row_iter_next, &[f64::from(iter)]) as i32 != 0 {
            let _ = vt.call(
                &vt.row_get,
                &[
                    f64::from(iter),
                    RENDER_STATE_ROW_DATA_CELLS,
                    f64::from(self.cells_slot),
                ],
            );
            let cell_iter = vt.r_u32(self.cells_slot);
            let mut n: u16 = 0;
            while vt.call(&vt.cells_next, &[f64::from(cell_iter)]) as i32 != 0 {
                cells.push(GridCell {
                    ch: self.cell_base_char(cell_iter),
                    fg: self.cell_color(cell_iter, ROW_CELLS_DATA_FG_COLOR),
                    bg: self.cell_color(cell_iter, ROW_CELLS_DATA_BG_COLOR),
                });
                n += 1;
            }
            // Keep the grid rectangular: pad short rows out to `cols`.
            while n < cols {
                cells.push(GridCell {
                    ch: ' ',
                    fg: None,
                    bg: None,
                });
                n += 1;
            }
        }

        // Cursor position + visibility, read straight off the terminal.
        let cursor_col = self.term_u32(TERMINAL_DATA_CURSOR_X) as u16;
        let cursor_row = self.term_u32(TERMINAL_DATA_CURSOR_Y) as u16;
        let cursor_visible = self.term_u32(TERMINAL_DATA_CURSOR_VISIBLE) != 0;

        Grid {
            cols,
            rows,
            default_fg,
            default_bg,
            cells,
            cursor_col,
            cursor_row,
            cursor_visible,
        }
    }

    /// Read a u32-valued terminal data field via `ghostty_terminal_get`.
    /// Zeroes the scratch first so a narrower write (e.g. a bool) reads cleanly.
    fn term_u32(&self, tag: f64) -> u32 {
        let vt = &*self.vt;
        vt.w_u32(self.scratch, 0);
        let _ = vt.call(
            &vt.terminal_get,
            &[f64::from(self.term), tag, f64::from(self.scratch)],
        );
        vt.r_u32(self.scratch)
    }

    fn rs_u32(&self, tag: f64) -> u32 {
        let vt = &*self.vt;
        let _ = vt.call(
            &vt.rs_get,
            &[f64::from(self.state), tag, f64::from(self.scratch)],
        );
        vt.r_u32(self.scratch)
    }

    fn rs_color(&self, tag: f64) -> Option<Rgb> {
        let vt = &*self.vt;
        let r = vt.call(
            &vt.rs_get,
            &[f64::from(self.state), tag, f64::from(self.scratch)],
        ) as i32;
        (r == GHOSTTY_SUCCESS).then(|| self.read_rgb(self.scratch))
    }

    fn cell_color(&self, cells: u32, tag: f64) -> Option<Rgb> {
        let vt = &*self.vt;
        let r = vt.call(
            &vt.cells_get,
            &[f64::from(cells), tag, f64::from(self.scratch)],
        ) as i32;
        (r == GHOSTTY_SUCCESS).then(|| self.read_rgb(self.scratch))
    }

    fn read_rgb(&self, ptr: u32) -> Rgb {
        let vt = &*self.vt;
        Rgb {
            r: vt.r_u8(ptr),
            g: vt.r_u8(ptr + 1),
            b: vt.r_u8(ptr + 2),
        }
    }
}

impl Drop for Terminal {
    fn drop(&mut self) {
        let _ = self
            .vt
            .call(&self.vt.terminal_free, &[f64::from(self.term)]);
    }
}
