#!/usr/bin/env bash
# Generate the Homebrew formula for phux from release artifacts.
#
# Usage: scripts/gen-formula.sh <tag> <dist-dir> [out-file]
#   <tag>       e.g. v0.0.1
#   <dist-dir>  directory holding phux-<tag>-<target>.tar.gz.sha256 files
#   [out-file]  defaults to stdout
#
# Only emits a download block for each target whose .sha256 file is present,
# so a partial release (e.g. only the macOS arm64 artifact built) still yields
# a valid, installable formula. Shared by release.yml and local seeding so the
# two paths never drift.
set -euo pipefail

tag="${1:?usage: gen-formula.sh <tag> <dist-dir> [out-file]}"
dist="${2:?usage: gen-formula.sh <tag> <dist-dir> [out-file]}"
version="${tag#v}"
base="https://github.com/phall1/phux/releases/download/${tag}"

# sha <target> -> prints the checksum, or empty string if the artifact is absent.
sha() {
  local f="${dist}/phux-${tag}-$1.tar.gz.sha256"
  [ -f "$f" ] && cut -d' ' -f1 < "$f" || true
}

arm_mac="$(sha aarch64-apple-darwin)"
x86_mac="$(sha x86_64-apple-darwin)"
x86_linux="$(sha x86_64-unknown-linux-gnu)"
arm_linux="$(sha aarch64-unknown-linux-gnu)"

if [ -z "${arm_mac}${x86_mac}${x86_linux}${arm_linux}" ]; then
  echo "error: no artifacts found in ${dist} for ${tag}" >&2
  exit 1
fi

primary_target=""
primary_sha=""
if [ -n "$arm_mac" ]; then
  primary_target="aarch64-apple-darwin"
  primary_sha="$arm_mac"
elif [ -n "$x86_mac" ]; then
  primary_target="x86_64-apple-darwin"
  primary_sha="$x86_mac"
elif [ -n "$x86_linux" ]; then
  primary_target="x86_64-unknown-linux-gnu"
  primary_sha="$x86_linux"
elif [ -n "$arm_linux" ]; then
  primary_target="aarch64-unknown-linux-gnu"
  primary_sha="$arm_linux"
fi

emit() {
  cat <<EOF
# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/phall1/phux"
  version "${version}"
  license any_of: ["MIT", "Apache-2.0"]
  url "${base}/phux-${tag}-${primary_target}.tar.gz"
  sha256 "${primary_sha}"

EOF

  if [ -n "${arm_mac}${x86_mac}" ]; then
    echo "  on_macos do"
    if [ -n "${arm_mac}" ]; then
      echo "    on_arm do"
      echo "      url \"${base}/phux-${tag}-aarch64-apple-darwin.tar.gz\""
      echo "      sha256 \"${arm_mac}\""
      echo "    end"
    fi
    if [ -n "${x86_mac}" ]; then
      echo "    on_intel do"
      echo "      url \"${base}/phux-${tag}-x86_64-apple-darwin.tar.gz\""
      echo "      sha256 \"${x86_mac}\""
      echo "    end"
    fi
    echo "  end"
    echo ""
  fi

  if [ -n "${x86_linux}${arm_linux}" ]; then
    echo "  on_linux do"
    if [ -n "${x86_linux}" ]; then
      echo "    on_intel do"
      echo "      url \"${base}/phux-${tag}-x86_64-unknown-linux-gnu.tar.gz\""
      echo "      sha256 \"${x86_linux}\""
      echo "    end"
    fi
    if [ -n "${arm_linux}" ]; then
      echo "    on_arm do"
      echo "      url \"${base}/phux-${tag}-aarch64-unknown-linux-gnu.tar.gz\""
      echo "      sha256 \"${arm_linux}\""
      echo "    end"
    fi
    echo "  end"
    echo ""
  fi

  cat <<'EOF'
  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
EOF
}

out="${3:-}"
if [ -n "$out" ]; then
  emit > "$out"
  echo "wrote $out" >&2
else
  emit
fi
