//! Key event translation: wire → libghostty-vt.
//!
//! ADR-0006 prescribes that [`PhysicalKey`](phux_protocol::input::key::PhysicalKey)
//! / [`KeyAction`](phux_protocol::input::key::KeyAction) /
//! [`ModSet`](phux_protocol::input::key::ModSet) mirror libghostty's
//! `key::Key` / `key::Action` / `key::Mods` one-to-one. `PhysicalKey`
//! discriminants do match libghostty's exactly (177 variants, pinned by
//! [`tests::physical_key_discriminants_match_libghostty`]), but
//! `KeyAction` and `Mods` ship with different numeric layouts in the live
//! libghostty rev — see [`key_action_to_libghostty`] and
//! [`modset_to_libghostty`] for the explicit semantic remap that this
//! module performs.
//!
//! [`PerPaneKeyEncoder`] owns the per-pane `libghostty_vt::key::Encoder` plus a
//! reusable byte buffer — call [`PerPaneKeyEncoder::encode`] with the pane's
//! current [`Terminal`] and the wire event; the returned `&[u8]` is the PTY
//! payload.

use libghostty_vt::{
    Error, Terminal,
    key::{Action as LgAction, Encoder as LgKeyEncoder, Event as LgKeyEvent, Key as LgKey, Mods},
};
use phux_protocol::input::key::{KeyAction, KeyEvent, ModSet, PhysicalKey};

/// Convert a wire [`KeyAction`] to libghostty's [`LgAction`].
///
/// ADR-0006 implied discriminant equality but in the live rev libghostty
/// has Release=0, Press=1, Repeat=2 while the wire has Press=0, Release=1,
/// Repeat=2. The match arms here do the semantic remap.
#[must_use]
pub const fn key_action_to_libghostty(action: KeyAction) -> LgAction {
    match action {
        KeyAction::Press => LgAction::Press,
        KeyAction::Release => LgAction::Release,
        KeyAction::Repeat => LgAction::Repeat,
    }
}

/// Convert a wire [`ModSet`] to libghostty's [`Mods`].
///
/// ADR-0006 claims bit-for-bit equivalence, but the live bit layouts differ:
/// libghostty orders `SHIFT|CTRL|ALT|SUPER|...` while phux-protocol orders
/// `SHIFT|ALT|CTRL|SUPER|...` (`CTRL` and `ALT` are swapped, and the
/// `*_SIDE` bits follow suit). This function does the explicit semantic
/// remap so the server-side encoder sees the correct modifier set. The
/// `modset_semantic_round_trip` test pins the contract.
#[must_use]
pub fn modset_to_libghostty(mods: ModSet) -> Mods {
    let mut out = Mods::empty();
    if mods.contains(ModSet::SHIFT) {
        out |= Mods::SHIFT;
    }
    if mods.contains(ModSet::ALT) {
        out |= Mods::ALT;
    }
    if mods.contains(ModSet::CTRL) {
        out |= Mods::CTRL;
    }
    if mods.contains(ModSet::SUPER) {
        out |= Mods::SUPER;
    }
    if mods.contains(ModSet::CAPS_LOCK) {
        out |= Mods::CAPS_LOCK;
    }
    if mods.contains(ModSet::NUM_LOCK) {
        out |= Mods::NUM_LOCK;
    }
    if mods.contains(ModSet::SHIFT_SIDE) {
        out |= Mods::SHIFT_SIDE;
    }
    if mods.contains(ModSet::ALT_SIDE) {
        out |= Mods::ALT_SIDE;
    }
    if mods.contains(ModSet::CTRL_SIDE) {
        out |= Mods::CTRL_SIDE;
    }
    if mods.contains(ModSet::SUPER_SIDE) {
        out |= Mods::SUPER_SIDE;
    }
    out
}

/// Convert a wire [`PhysicalKey`] to libghostty's [`LgKey`].
///
/// Discriminants are pinned equal to libghostty's by phux-protocol's
/// `physical_key_discriminants_match_libghostty` test (mirrored here as a live
/// check). For the rare case libghostty adds a variant we haven't seen,
/// this falls back to [`LgKey::Unidentified`].
#[must_use]
#[allow(
    clippy::missing_panics_doc,
    reason = "infallible by construction — discriminants are pinned by test"
)]
pub fn physical_key_to_libghostty(key: PhysicalKey) -> LgKey {
    // PhysicalKey is `#[repr(u32)]` with discriminants matching `LgKey`.
    // `LgKey::try_from` is generated by `int_enum::IntEnum`.
    LgKey::try_from(key as u32).unwrap_or(LgKey::Unidentified)
}

/// Fallible conversion from a wire [`KeyEvent`] to libghostty's [`LgKeyEvent`].
///
/// Orphan-rules prevent us from offering this as a trait impl (`KeyEvent`
/// and `LgKeyEvent` both live outside this crate). Fallibility comes from
/// libghostty's FFI allocator — the field copy itself is total. ADR-0006
/// described this as a `From`-style conversion; this free function is the
/// realized shape.
pub fn key_event_to_libghostty(ev: &KeyEvent) -> Result<LgKeyEvent<'static>, Error> {
    let mut out = LgKeyEvent::new()?;
    out.set_action(key_action_to_libghostty(ev.action))
        .set_key(physical_key_to_libghostty(ev.key))
        .set_mods(modset_to_libghostty(ev.mods))
        .set_consumed_mods(modset_to_libghostty(ev.consumed_mods))
        .set_composing(ev.composing)
        .set_utf8(ev.text.clone());
    if let Some(cp) = ev.unshifted_codepoint
        && let Some(ch) = char::from_u32(cp)
    {
        out.set_unshifted_codepoint(ch);
    }
    Ok(out)
}

/// Per-pane key encoder.
///
/// Owns one `libghostty_vt::key::Encoder` plus a growable byte buffer reused
/// across calls. Per-pane: each pane should hold its own instance so encoder
/// state (KIP flags, modifyOtherKeys, etc.) reflects only that pane's
/// terminal state. See ADR-0006 §"Encoder options stay server-local".
#[derive(Debug)]
pub struct PerPaneKeyEncoder {
    encoder: LgKeyEncoder<'static>,
    buf: Vec<u8>,
}

impl PerPaneKeyEncoder {
    /// Construct a new per-pane key encoder with a fresh libghostty allocator.
    pub fn new() -> Result<Self, Error> {
        Ok(Self {
            encoder: LgKeyEncoder::new()?,
            buf: Vec::with_capacity(32),
        })
    }

    /// Encode a wire key event into PTY bytes.
    ///
    /// Refreshes encoder options from `terminal` (cursor key application
    /// mode, keypad mode, modifyOtherKeys, KIP flags, alt-esc-prefix,
    /// backarrow — see ADR-0006) before each encode so the bytes match
    /// what the inner program currently expects.
    ///
    /// Returns a slice borrowed from `self`'s internal buffer; the slice is
    /// valid until the next call to `encode`.
    pub fn encode(
        &mut self,
        event: &KeyEvent,
        terminal: &Terminal<'_, '_>,
    ) -> Result<&[u8], Error> {
        let lg_event = key_event_to_libghostty(event)?;
        self.encoder.set_options_from_terminal(terminal);
        self.buf.clear();
        self.encoder.encode_to_vec(&lg_event, &mut self.buf)?;
        Ok(&self.buf)
    }
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::too_many_lines, reason = "tests")]
mod tests {
    use super::*;
    use libghostty_vt::TerminalOptions;

    fn make_terminal() -> Terminal<'static, 'static> {
        Terminal::new(TerminalOptions {
            cols: 80,
            rows: 24,
            max_scrollback: 1000,
        })
        .expect("Terminal::new")
    }

    #[test]
    fn key_event_to_libghostty_round_trips_fields() {
        let ev = KeyEvent {
            action: KeyAction::Press,
            key: PhysicalKey::A,
            mods: ModSet::CTRL | ModSet::SHIFT,
            consumed_mods: ModSet::SHIFT,
            composing: false,
            text: Some("A".to_owned()),
            unshifted_codepoint: Some(u32::from('a')),
        };
        let mut lg = key_event_to_libghostty(&ev).expect("convert");
        assert_eq!(lg.action(), LgAction::Press);
        assert_eq!(lg.key(), LgKey::A);
        assert_eq!(lg.mods(), Mods::CTRL | Mods::SHIFT);
        assert_eq!(lg.consumed_mods(), Mods::SHIFT);
        assert!(!lg.is_composing());
        assert_eq!(lg.utf8(), Some("A"));
        assert_eq!(lg.unshifted_codepoint(), 'a');
    }

    #[test]
    fn encodes_plain_letter_a_to_byte_a() {
        let terminal = make_terminal();
        let mut enc = PerPaneKeyEncoder::new().expect("encoder");
        let ev = KeyEvent {
            action: KeyAction::Press,
            key: PhysicalKey::A,
            mods: ModSet::empty(),
            consumed_mods: ModSet::empty(),
            composing: false,
            text: Some("a".to_owned()),
            unshifted_codepoint: Some(u32::from('a')),
        };
        let bytes = enc.encode(&ev, &terminal).expect("encode");
        assert!(
            bytes.starts_with(b"a"),
            "expected encoded bytes to start with `a`, got {bytes:?}"
        );
    }

    /// Cross-crate discriminant check (the live version of the table-driven
    /// test in `phux-protocol::input::key::tests::physical_key_discriminants_match_libghostty`).
    ///
    /// phux-protocol cannot depend on libghostty-vt (layering), so it pins
    /// discriminants with a hard-coded table. This test re-runs that table
    /// against the actual libghostty enum — if either side drifts, this
    /// fails.
    #[test]
    #[allow(
        clippy::too_many_lines,
        reason = "exhaustive — one line per PhysicalKey variant"
    )]
    fn physical_key_discriminants_match_libghostty() {
        const PAIRS: &[(PhysicalKey, LgKey)] = &[
            (PhysicalKey::Unidentified, LgKey::Unidentified),
            (PhysicalKey::Backquote, LgKey::Backquote),
            (PhysicalKey::Backslash, LgKey::Backslash),
            (PhysicalKey::BracketLeft, LgKey::BracketLeft),
            (PhysicalKey::BracketRight, LgKey::BracketRight),
            (PhysicalKey::Comma, LgKey::Comma),
            (PhysicalKey::Digit0, LgKey::Digit0),
            (PhysicalKey::Digit1, LgKey::Digit1),
            (PhysicalKey::Digit2, LgKey::Digit2),
            (PhysicalKey::Digit3, LgKey::Digit3),
            (PhysicalKey::Digit4, LgKey::Digit4),
            (PhysicalKey::Digit5, LgKey::Digit5),
            (PhysicalKey::Digit6, LgKey::Digit6),
            (PhysicalKey::Digit7, LgKey::Digit7),
            (PhysicalKey::Digit8, LgKey::Digit8),
            (PhysicalKey::Digit9, LgKey::Digit9),
            (PhysicalKey::Equal, LgKey::Equal),
            (PhysicalKey::IntlBackslash, LgKey::IntlBackslash),
            (PhysicalKey::IntlRo, LgKey::IntlRo),
            (PhysicalKey::IntlYen, LgKey::IntlYen),
            (PhysicalKey::A, LgKey::A),
            (PhysicalKey::B, LgKey::B),
            (PhysicalKey::C, LgKey::C),
            (PhysicalKey::D, LgKey::D),
            (PhysicalKey::E, LgKey::E),
            (PhysicalKey::F, LgKey::F),
            (PhysicalKey::G, LgKey::G),
            (PhysicalKey::H, LgKey::H),
            (PhysicalKey::I, LgKey::I),
            (PhysicalKey::J, LgKey::J),
            (PhysicalKey::K, LgKey::K),
            (PhysicalKey::L, LgKey::L),
            (PhysicalKey::M, LgKey::M),
            (PhysicalKey::N, LgKey::N),
            (PhysicalKey::O, LgKey::O),
            (PhysicalKey::P, LgKey::P),
            (PhysicalKey::Q, LgKey::Q),
            (PhysicalKey::R, LgKey::R),
            (PhysicalKey::S, LgKey::S),
            (PhysicalKey::T, LgKey::T),
            (PhysicalKey::U, LgKey::U),
            (PhysicalKey::V, LgKey::V),
            (PhysicalKey::W, LgKey::W),
            (PhysicalKey::X, LgKey::X),
            (PhysicalKey::Y, LgKey::Y),
            (PhysicalKey::Z, LgKey::Z),
            (PhysicalKey::Minus, LgKey::Minus),
            (PhysicalKey::Period, LgKey::Period),
            (PhysicalKey::Quote, LgKey::Quote),
            (PhysicalKey::Semicolon, LgKey::Semicolon),
            (PhysicalKey::Slash, LgKey::Slash),
            (PhysicalKey::AltLeft, LgKey::AltLeft),
            (PhysicalKey::AltRight, LgKey::AltRight),
            (PhysicalKey::Backspace, LgKey::Backspace),
            (PhysicalKey::CapsLock, LgKey::CapsLock),
            (PhysicalKey::ContextMenu, LgKey::ContextMenu),
            (PhysicalKey::ControlLeft, LgKey::ControlLeft),
            (PhysicalKey::ControlRight, LgKey::ControlRight),
            (PhysicalKey::Enter, LgKey::Enter),
            (PhysicalKey::MetaLeft, LgKey::MetaLeft),
            (PhysicalKey::MetaRight, LgKey::MetaRight),
            (PhysicalKey::ShiftLeft, LgKey::ShiftLeft),
            (PhysicalKey::ShiftRight, LgKey::ShiftRight),
            (PhysicalKey::Space, LgKey::Space),
            (PhysicalKey::Tab, LgKey::Tab),
            (PhysicalKey::Convert, LgKey::Convert),
            (PhysicalKey::KanaMode, LgKey::KanaMode),
            (PhysicalKey::NonConvert, LgKey::NonConvert),
            (PhysicalKey::Delete, LgKey::Delete),
            (PhysicalKey::End, LgKey::End),
            (PhysicalKey::Help, LgKey::Help),
            (PhysicalKey::Home, LgKey::Home),
            (PhysicalKey::Insert, LgKey::Insert),
            (PhysicalKey::PageDown, LgKey::PageDown),
            (PhysicalKey::PageUp, LgKey::PageUp),
            (PhysicalKey::ArrowDown, LgKey::ArrowDown),
            (PhysicalKey::ArrowLeft, LgKey::ArrowLeft),
            (PhysicalKey::ArrowRight, LgKey::ArrowRight),
            (PhysicalKey::ArrowUp, LgKey::ArrowUp),
            (PhysicalKey::NumLock, LgKey::NumLock),
            (PhysicalKey::Numpad0, LgKey::Numpad0),
            (PhysicalKey::Numpad1, LgKey::Numpad1),
            (PhysicalKey::Numpad2, LgKey::Numpad2),
            (PhysicalKey::Numpad3, LgKey::Numpad3),
            (PhysicalKey::Numpad4, LgKey::Numpad4),
            (PhysicalKey::Numpad5, LgKey::Numpad5),
            (PhysicalKey::Numpad6, LgKey::Numpad6),
            (PhysicalKey::Numpad7, LgKey::Numpad7),
            (PhysicalKey::Numpad8, LgKey::Numpad8),
            (PhysicalKey::Numpad9, LgKey::Numpad9),
            (PhysicalKey::NumpadAdd, LgKey::NumpadAdd),
            (PhysicalKey::NumpadBackspace, LgKey::NumpadBackspace),
            (PhysicalKey::NumpadClear, LgKey::NumpadClear),
            (PhysicalKey::NumpadClearEntry, LgKey::NumpadClearEntry),
            (PhysicalKey::NumpadComma, LgKey::NumpadComma),
            (PhysicalKey::NumpadDecimal, LgKey::NumpadDecimal),
            (PhysicalKey::NumpadDivide, LgKey::NumpadDivide),
            (PhysicalKey::NumpadEnter, LgKey::NumpadEnter),
            (PhysicalKey::NumpadEqual, LgKey::NumpadEqual),
            (PhysicalKey::NumpadMemoryAdd, LgKey::NumpadMemoryAdd),
            (PhysicalKey::NumpadMemoryClear, LgKey::NumpadMemoryClear),
            (PhysicalKey::NumpadMemoryRecall, LgKey::NumpadMemoryRecall),
            (PhysicalKey::NumpadMemoryStore, LgKey::NumpadMemoryStore),
            (
                PhysicalKey::NumpadMemorySubtract,
                LgKey::NumpadMemorySubtract,
            ),
            (PhysicalKey::NumpadMultiply, LgKey::NumpadMultiply),
            (PhysicalKey::NumpadParenLeft, LgKey::NumpadParenLeft),
            (PhysicalKey::NumpadParenRight, LgKey::NumpadParenRight),
            (PhysicalKey::NumpadSubtract, LgKey::NumpadSubtract),
            (PhysicalKey::NumpadSeparator, LgKey::NumpadSeparator),
            (PhysicalKey::NumpadUp, LgKey::NumpadUp),
            (PhysicalKey::NumpadDown, LgKey::NumpadDown),
            (PhysicalKey::NumpadRight, LgKey::NumpadRight),
            (PhysicalKey::NumpadLeft, LgKey::NumpadLeft),
            (PhysicalKey::NumpadBegin, LgKey::NumpadBegin),
            (PhysicalKey::NumpadHome, LgKey::NumpadHome),
            (PhysicalKey::NumpadEnd, LgKey::NumpadEnd),
            (PhysicalKey::NumpadInsert, LgKey::NumpadInsert),
            (PhysicalKey::NumpadDelete, LgKey::NumpadDelete),
            (PhysicalKey::NumpadPageUp, LgKey::NumpadPageUp),
            (PhysicalKey::NumpadPageDown, LgKey::NumpadPageDown),
            (PhysicalKey::Escape, LgKey::Escape),
            (PhysicalKey::F1, LgKey::F1),
            (PhysicalKey::F2, LgKey::F2),
            (PhysicalKey::F3, LgKey::F3),
            (PhysicalKey::F4, LgKey::F4),
            (PhysicalKey::F5, LgKey::F5),
            (PhysicalKey::F6, LgKey::F6),
            (PhysicalKey::F7, LgKey::F7),
            (PhysicalKey::F8, LgKey::F8),
            (PhysicalKey::F9, LgKey::F9),
            (PhysicalKey::F10, LgKey::F10),
            (PhysicalKey::F11, LgKey::F11),
            (PhysicalKey::F12, LgKey::F12),
            (PhysicalKey::F13, LgKey::F13),
            (PhysicalKey::F14, LgKey::F14),
            (PhysicalKey::F15, LgKey::F15),
            (PhysicalKey::F16, LgKey::F16),
            (PhysicalKey::F17, LgKey::F17),
            (PhysicalKey::F18, LgKey::F18),
            (PhysicalKey::F19, LgKey::F19),
            (PhysicalKey::F20, LgKey::F20),
            (PhysicalKey::F21, LgKey::F21),
            (PhysicalKey::F22, LgKey::F22),
            (PhysicalKey::F23, LgKey::F23),
            (PhysicalKey::F24, LgKey::F24),
            (PhysicalKey::F25, LgKey::F25),
            (PhysicalKey::Fn, LgKey::Fn),
            (PhysicalKey::FnLock, LgKey::FnLock),
            (PhysicalKey::PrintScreen, LgKey::PrintScreen),
            (PhysicalKey::ScrollLock, LgKey::ScrollLock),
            (PhysicalKey::Pause, LgKey::Pause),
            (PhysicalKey::BrowserBack, LgKey::BrowserBack),
            (PhysicalKey::BrowserFavorites, LgKey::BrowserFavorites),
            (PhysicalKey::BrowserForward, LgKey::BrowserForward),
            (PhysicalKey::BrowserHome, LgKey::BrowserHome),
            (PhysicalKey::BrowserRefresh, LgKey::BrowserRefresh),
            (PhysicalKey::BrowserSearch, LgKey::BrowserSearch),
            (PhysicalKey::BrowserStop, LgKey::BrowserStop),
            (PhysicalKey::Eject, LgKey::Eject),
            (PhysicalKey::LaunchApp1, LgKey::LaunchApp1),
            (PhysicalKey::LaunchApp2, LgKey::LaunchApp2),
            (PhysicalKey::LaunchMail, LgKey::LaunchMail),
            (PhysicalKey::MediaPlayPause, LgKey::MediaPlayPause),
            (PhysicalKey::MediaSelect, LgKey::MediaSelect),
            (PhysicalKey::MediaStop, LgKey::MediaStop),
            (PhysicalKey::MediaTrackNext, LgKey::MediaTrackNext),
            (PhysicalKey::MediaTrackPrevious, LgKey::MediaTrackPrevious),
            (PhysicalKey::Power, LgKey::Power),
            (PhysicalKey::Sleep, LgKey::Sleep),
            (PhysicalKey::AudioVolumeDown, LgKey::AudioVolumeDown),
            (PhysicalKey::AudioVolumeMute, LgKey::AudioVolumeMute),
            (PhysicalKey::AudioVolumeUp, LgKey::AudioVolumeUp),
            (PhysicalKey::WakeUp, LgKey::WakeUp),
            (PhysicalKey::Copy, LgKey::Copy),
            (PhysicalKey::Cut, LgKey::Cut),
            (PhysicalKey::Paste, LgKey::Paste),
        ];
        assert_eq!(PAIRS.len(), 176, "expected all 176 PhysicalKey variants");
        for &(wire, lg) in PAIRS {
            assert_eq!(
                wire as u32,
                lg as u32,
                "discriminant mismatch: {wire:?} ({wire_d}) vs {lg:?} ({lg_d})",
                wire_d = wire as u32,
                lg_d = lg as u32,
            );
        }
    }

    /// Semantic equivalence: each wire [`KeyAction`] variant routes to the
    /// correct libghostty [`LgAction`] variant. ADR-0006 implied
    /// discriminant equality, but the live values differ (libghostty:
    /// Release=0, Press=1, Repeat=2 vs. wire: Press=0, Release=1,
    /// Repeat=2). The conversion function compensates; this test pins the
    /// semantic mapping rather than numeric equality.
    #[test]
    fn key_action_semantic_mapping_is_correct() {
        assert_eq!(key_action_to_libghostty(KeyAction::Press), LgAction::Press);
        assert_eq!(
            key_action_to_libghostty(KeyAction::Release),
            LgAction::Release
        );
        assert_eq!(
            key_action_to_libghostty(KeyAction::Repeat),
            LgAction::Repeat
        );
    }

    /// Semantic equivalence for [`ModSet`] → [`Mods`]. ADR-0006 implied
    /// bit-for-bit equality, but live layouts differ
    /// (libghostty: SHIFT=1, CTRL=2, ALT=4; wire: SHIFT=1, ALT=2, CTRL=4 —
    /// CTRL/ALT swapped, and `*_SIDE` shifts follow). `modset_to_libghostty`
    /// does the explicit remap; this test pins each flag's
    /// post-conversion identity.
    #[test]
    fn modset_semantic_round_trip() {
        let pairs: &[(ModSet, Mods)] = &[
            (ModSet::SHIFT, Mods::SHIFT),
            (ModSet::ALT, Mods::ALT),
            (ModSet::CTRL, Mods::CTRL),
            (ModSet::SUPER, Mods::SUPER),
            (ModSet::CAPS_LOCK, Mods::CAPS_LOCK),
            (ModSet::NUM_LOCK, Mods::NUM_LOCK),
            (ModSet::SHIFT_SIDE, Mods::SHIFT_SIDE),
            (ModSet::ALT_SIDE, Mods::ALT_SIDE),
            (ModSet::CTRL_SIDE, Mods::CTRL_SIDE),
            (ModSet::SUPER_SIDE, Mods::SUPER_SIDE),
        ];
        for &(wire, lg) in pairs {
            assert_eq!(
                modset_to_libghostty(wire),
                lg,
                "wire {wire:?} should map to libghostty {lg:?}",
            );
        }
        // Combined: SHIFT | CTRL on the wire becomes SHIFT | CTRL in libghostty.
        assert_eq!(
            modset_to_libghostty(ModSet::SHIFT | ModSet::CTRL),
            Mods::SHIFT | Mods::CTRL,
        );
    }
}
